services:
  - type: web
    name: ai-interview-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: XFYUN_APP_ID
        sync: false
      - key: XFYUN_API_KEY
        sync: false
      - key: XFYUN_API_SECRET
        sync: false 